# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    firewalls:       
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login      
            logout:
                path:   /logout
                target: /login
    
    access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
    - { path: ^/, roles: ROLE_ADMIN }
         

    providers:
        in_memory:
            memory:
                users:
                    Mitarbeiter:
                        password: pass
                        roles: 'ROLE_ADMIN'
                    Chef:
                        password: admin
                        roles: 'ROLE_ADMIN' 
    encoders:
         Symfony\Component\Security\Core\User\User: plaintext

          
   
        
    
    

