# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
               
        default:
            anonymous: ~
            http_basic:
                provider: in_memory
                
            
        main:
            anonymous: ~
            
            
    providers:
        in_memory:
            memory:
                users:
                    ryan:
                        password: ryanpass
                        roles: 'ROLE_USER'
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'
            
   
        
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
            
            
          
   
        
    
    

